version: '3.8'

services: #Servicios que corremos en nuestra red de docker.
  app:
    build:
      context: ./docker/python  #AQUI VIENEN LOS PROBLEMAS :)
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=development
    #volumes:
    #  - .:/app
    depends_on:
      - db

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: microblogging
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: